// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfProcessKey struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type bpfTrafficStats struct {
	_       structs.HostLayout
	TxBytes uint64
	RxBytes uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeTcpCleanupRbuf *ebpf.ProgramSpec `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg     *ebpf.ProgramSpec `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg     *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	KretprobeUdpRecvmsg  *ebpf.ProgramSpec `ebpf:"kretprobe_udp_recvmsg"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveUdpReads *ebpf.MapSpec `ebpf:"active_udp_reads"`
	ProcStats      *ebpf.MapSpec `ebpf:"proc_stats"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveUdpReads *ebpf.Map `ebpf:"active_udp_reads"`
	ProcStats      *ebpf.Map `ebpf:"proc_stats"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveUdpReads,
		m.ProcStats,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeTcpCleanupRbuf *ebpf.Program `ebpf:"kprobe_tcp_cleanup_rbuf"`
	KprobeTcpSendmsg     *ebpf.Program `ebpf:"kprobe_tcp_sendmsg"`
	KprobeUdpRecvmsg     *ebpf.Program `ebpf:"kprobe_udp_recvmsg"`
	KprobeUdpSendmsg     *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	KretprobeUdpRecvmsg  *ebpf.Program `ebpf:"kretprobe_udp_recvmsg"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeTcpCleanupRbuf,
		p.KprobeTcpSendmsg,
		p.KprobeUdpRecvmsg,
		p.KprobeUdpSendmsg,
		p.KretprobeUdpRecvmsg,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
